/**
 * Master Skill Catalogue — Frontend
 * ~250 skills, domain-mapped, weight 1–5 (mirrors server/utils/skillCatalogue.js)
 * Used by: MySkills dropdown, readiness score display
 */

export const SKILL_CATALOGUE = {
  Frontend: [
    { name: 'React.js',         weight: 5 },
    { name: 'Next.js',          weight: 5 },
    { name: 'TypeScript',       weight: 5 },
    { name: 'JavaScript',       weight: 5 },
    { name: 'HTML',             weight: 3 },
    { name: 'CSS',              weight: 3 },
    { name: 'TailwindCSS',      weight: 4 },
    { name: 'Vue.js',           weight: 4 },
    { name: 'Angular',          weight: 4 },
    { name: 'Svelte',           weight: 3 },
    { name: 'Redux',            weight: 4 },
    { name: 'Zustand',          weight: 3 },
    { name: 'React Query',      weight: 4 },
    { name: 'GraphQL (client)', weight: 4 },
    { name: 'Webpack',          weight: 3 },
    { name: 'Vite',             weight: 3 },
    { name: 'Storybook',        weight: 3 },
    { name: 'Jest',             weight: 4 },
    { name: 'Cypress',          weight: 3 },
    { name: 'Playwright',       weight: 3 },
    { name: 'SASS/SCSS',        weight: 2 },
    { name: 'Figma',            weight: 3 },
    { name: 'Three.js',         weight: 2 },
    { name: 'D3.js',            weight: 3 },
    { name: 'Framer Motion',    weight: 2 },
    { name: 'GSAP',             weight: 2 },
    { name: 'Material UI',      weight: 3 },
    { name: 'shadcn/ui',        weight: 3 },
  ],
  Backend: [
    { name: 'Node.js',          weight: 5 },
    { name: 'Express.js',       weight: 4 },
    { name: 'Python',           weight: 5 },
    { name: 'FastAPI',          weight: 4 },
    { name: 'Django',           weight: 4 },
    { name: 'Flask',            weight: 3 },
    { name: 'Java',             weight: 5 },
    { name: 'Spring Boot',      weight: 5 },
    { name: 'Go',               weight: 4 },
    { name: 'Rust',             weight: 3 },
    { name: 'C#',               weight: 4 },
    { name: '.NET Core',        weight: 4 },
    { name: 'REST API',         weight: 5 },
    { name: 'GraphQL',          weight: 4 },
    { name: 'gRPC',             weight: 3 },
    { name: 'WebSockets',       weight: 3 },
    { name: 'Microservices',    weight: 4 },
    { name: 'Apache Kafka',     weight: 4 },
    { name: 'RabbitMQ',         weight: 3 },
    { name: 'Firebase',         weight: 3 },
    { name: 'Socket.io',        weight: 3 },
    { name: 'Nginx',            weight: 3 },
    { name: 'Apache Spark',     weight: 3 },
    { name: 'Solidity',         weight: 2 },
  ],
  Database: [
    { name: 'SQL',              weight: 5 },
    { name: 'PostgreSQL',       weight: 5 },
    { name: 'MySQL',            weight: 4 },
    { name: 'MongoDB',          weight: 4 },
    { name: 'SQLite',           weight: 2 },
    { name: 'Redis',            weight: 4 },
    { name: 'Elasticsearch',    weight: 4 },
    { name: 'DynamoDB',         weight: 3 },
    { name: 'Cassandra',        weight: 3 },
    { name: 'Firestore',        weight: 3 },
    { name: 'Prisma ORM',       weight: 3 },
    { name: 'TypeORM',          weight: 3 },
    { name: 'Mongoose',         weight: 3 },
    { name: 'Database Design',  weight: 4 },
    { name: 'Query Optimisation', weight: 4 },
  ],
  'AI/ML': [
    { name: 'Machine Learning', weight: 5 },
    { name: 'Deep Learning',    weight: 5 },
    { name: 'TensorFlow',       weight: 5 },
    { name: 'PyTorch',          weight: 5 },
    { name: 'Scikit-learn',     weight: 4 },
    { name: 'Pandas',           weight: 4 },
    { name: 'NumPy',            weight: 4 },
    { name: 'Matplotlib',       weight: 3 },
    { name: 'Statistics',       weight: 4 },
    { name: 'NLP',              weight: 4 },
    { name: 'Computer Vision',  weight: 4 },
    { name: 'Transformers',     weight: 5 },
    { name: 'LangChain',        weight: 4 },
    { name: 'OpenAI API',       weight: 4 },
    { name: 'Hugging Face',     weight: 4 },
    { name: 'MLflow',           weight: 3 },
    { name: 'Feature Engineering', weight: 4 },
    { name: 'Model Deployment', weight: 4 },
    { name: 'Time Series',      weight: 3 },
    { name: 'Tableau',          weight: 3 },
    { name: 'Power BI',         weight: 3 },
  ],
  DevOps: [
    { name: 'Docker',           weight: 5 },
    { name: 'Kubernetes',       weight: 5 },
    { name: 'CI/CD',            weight: 5 },
    { name: 'AWS',              weight: 5 },
    { name: 'Google Cloud',     weight: 4 },
    { name: 'Azure',            weight: 4 },
    { name: 'Terraform',        weight: 5 },
    { name: 'Ansible',          weight: 4 },
    { name: 'Helm',             weight: 3 },
    { name: 'Linux',            weight: 5 },
    { name: 'Bash Scripting',   weight: 4 },
    { name: 'GitHub Actions',   weight: 4 },
    { name: 'Jenkins',          weight: 3 },
    { name: 'ArgoCD',           weight: 3 },
    { name: 'Prometheus',       weight: 3 },
    { name: 'Grafana',          weight: 3 },
    { name: 'Git',              weight: 5 },
    { name: 'Serverless',       weight: 4 },
    { name: 'Security (DevSecOps)', weight: 4 },
  ],
  Mobile: [
    { name: 'Flutter',          weight: 5 },
    { name: 'Dart',             weight: 4 },
    { name: 'React Native',     weight: 5 },
    { name: 'Swift',            weight: 5 },
    { name: 'SwiftUI',          weight: 4 },
    { name: 'Kotlin',           weight: 5 },
    { name: 'Jetpack Compose',  weight: 4 },
    { name: 'Android SDK',      weight: 4 },
    { name: 'iOS SDK',          weight: 4 },
    { name: 'Expo',             weight: 3 },
    { name: 'Firebase',         weight: 3 },
    { name: 'App Store Deployment', weight: 3 },
  ],
  Language: [
    { name: 'Python',           weight: 5 },
    { name: 'JavaScript',       weight: 5 },
    { name: 'TypeScript',       weight: 5 },
    { name: 'Java',             weight: 5 },
    { name: 'C++',              weight: 4 },
    { name: 'C#',               weight: 4 },
    { name: 'Go',               weight: 4 },
    { name: 'Kotlin',           weight: 4 },
    { name: 'Swift',            weight: 4 },
    { name: 'Rust',             weight: 3 },
    { name: 'Dart',             weight: 3 },
    { name: 'PHP',              weight: 3 },
    { name: 'R',                weight: 3 },
    { name: 'Bash/Shell',       weight: 4 },
    { name: 'SQL',              weight: 5 },
  ],
  Design: [
    { name: 'Figma',            weight: 5 },
    { name: 'Adobe XD',         weight: 3 },
    { name: 'UI/UX Design',     weight: 4 },
    { name: 'Wireframing',      weight: 3 },
    { name: 'Prototyping',      weight: 3 },
    { name: 'User Research',    weight: 3 },
    { name: 'Design Systems',   weight: 4 },
    { name: 'Accessibility (a11y)', weight: 3 },
  ],
  Other: [
    { name: 'Git',              weight: 5 },
    { name: 'System Design',    weight: 5 },
    { name: 'Data Structures',  weight: 5 },
    { name: 'Algorithms',       weight: 5 },
    { name: 'Agile / Scrum',    weight: 4 },
    { name: 'Problem Solving',  weight: 5 },
    { name: 'Cybersecurity',    weight: 3 },
    { name: 'Ethical Hacking',  weight: 2 },
    { name: 'Unity',            weight: 2 },
    { name: 'IoT',              weight: 2 },
    { name: 'Blockchain',       weight: 2 },
  ],
}

// Flat list of all skill names, alphabetically sorted
export const ALL_SKILL_NAMES = Object.values(SKILL_CATALOGUE)
  .flat()
  .map(s => s.name)
  .filter((v, i, arr) => arr.indexOf(v) === i)   // deduplicate
  .sort((a, b) => a.localeCompare(b))

// Lookup: skill name (lowercase) → { category, weight }
export const SKILL_LOOKUP = {}
Object.entries(SKILL_CATALOGUE).forEach(([category, skills]) => {
  skills.forEach(s => {
    SKILL_LOOKUP[s.name.toLowerCase()] = { category, weight: s.weight, name: s.name }
  })
})

export default SKILL_CATALOGUE
